config/routes.rb
Gambit::Application.routes.draw do
  resources :players

  match "matches/admin" => "matches#admin"

  resources :matches

 root :to => "matches#index"
 

end

app/models/match.rb
class Match < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /matches
  # GET /matches.xml
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.xml
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.xml
  def new
    @match = Match.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.xml
  def create
    @match = Match.new(params[:match])

    respond_to do |format|
      if @match.save
        format.html { redirect_to(@match, :notice => 'Match was successfully created.') }
        format.xml  { render :xml => @match, :status => :created, :location => @match }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.xml
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to(@match, :notice => 'Match was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.xml
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to(matches_url) }
      format.xml  { head :ok }
    end
  end
  
  def match_admin
  
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.xml
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @players }
    end
  end

  # GET /players/1
  # GET /players/1.xml
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @player }
    end
  end

  # GET /players/new
  # GET /players/new.xml
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.xml
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to(@player, :notice => 'Player was successfully created.') }
        format.xml  { render :xml => @player, :status => :created, :location => @player }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.xml
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to(@player, :notice => 'Player was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.xml
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to(players_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gambit</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "gambit" %>  
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div id="logo"><%= link_to 'GG!', root_path, :class => 'gg'%><%= link_to ' gambit gaming', root_path %></div>
<br />
<div id="menubar">
<%= link_to 'MATCHES', matches_path %>
<%= link_to 'PLAYERS', players_path %>
<%= link_to 'ADMIN CONSOLE', matches_admin_path %>
</div>

<%= yield %>

</body>
</html>

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :game_time %><br />
    <%= f.datetime_select :game_time %>
  </div>
  <div class="field">
    <%= f.label :betting_close_time %><br />
    <%= f.datetime_select :betting_close_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/admin.html.erb
<h1>Match Admin Console</h1>

<%= link_to 'New Match' %><br />
<%= link_to 'New Player' %><br />

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<h2>MATCH OF THE DAY</h2>

<h2>ALL MATCHES</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Game time</th>
    <th>Betting close time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <td><%= match.name %></td>
    <td><%= match.description %></td>
    <td><%= match.game_time %></td>
    <td><%= match.betting_close_time %></td>
    <td><%= link_to 'Show', match %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
    <td><%= link_to 'Destroy', match, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Match', new_match_path %>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @match.name %>
</p>

<p>
  <b>Description:</b>
  <%= @match.description %>
</p>

<p>
  <b>Game time:</b>
  <%= @match.game_time %>
</p>

<p>
  <b>Betting close time:</b>
  <%= @match.betting_close_time %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br />
    <%= f.text_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :twitter %><br />
    <%= f.text_field :twitter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Team</th>
    <th>Description</th>
    <th>Url</th>
    <th>Twitter</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.name %></td>
    <td><%= player.team_id %></td>
    <td><%= player.description %></td>
    <td><%= player.url %></td>
    <td><%= player.twitter %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @player.name %>
</p>

<p>
  <b>Team:</b>
  <%= @player.team_id %>
</p>

<p>
  <b>Description:</b>
  <%= @player.description %>
</p>

<p>
  <b>Url:</b>
  <%= @player.url %>
</p>

<p>
  <b>Twitter:</b>
  <%= @player.twitter %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>